[project]
name = 'NewDonation'
description = ''
authors = []
telemetry = false
cache_dir = '.\.cache'
requirements = []
[contracts.donation]
path = 'contracts/donation.clar'

[contracts.sip-010ft]
path = 'contracts/sip-010ft.clar'

[contracts.dt]
path = 'contracts/dt.clar'


clarity_version = 2
epoch = 2.4
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
